In [186]:
import numpy as np
import collections

from numpy.testing import assert_allclose

# Part I. Construct a Householder reflection of a vector.

Given a vector $\mathbf{x}$, and a plane with a normal vector $\mathbf{u}$, the Householder transformation reflects $\mathbf{x}$ about the plane.

The matrix of the Householder transformation is

$$
\mathbf{H} = \mathbf{1} - 2 \mathbf{u} \mathbf{u}^T
$$

Given two equal-length vectors $\mathbf{x}$ and $\mathbf{y}$, a rotation which brings $\mathbf{x}$ to $\mathbf{y}$ is a Householder transform with

$$
\mathbf{u} = \frac{\mathbf{x} - \mathbf{y}}{||\mathbf{x} - \mathbf{y}||}
$$

In [187]:
def householder(vec):
    """Construct a Householder reflection to zero out 2nd and further components of a vector.

    Parameters
    ----------
    vec : array-like of floats, shape (n,)
        Input vector
    
    Returns
    -------
    outvec : array of floats, shape (n,)
        Transformed vector, with ``outvec[1:]==0`` and ``|outvec| == |vec|``
    H : array of floats, shape (n, n)
        Orthogonal matrix of the Householder reflection
    """
    vec = np.asarray(vec, dtype=float)
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)
    y = np.zeros((len(vec)))
    y[0] = np.linalg.norm(vec)
    u = vec - y
    u /= np.linalg.norm(u)
    
    H = np.zeros((len(vec),len(vec)))
    H = np.diag(np.ones(len(vec))) - 2* (u[:,None] @ u[:,None].T)
    res = H @ vec
   
    
    return res, H


In [189]:

v = np.array([1, 2, 3])
v1, h = householder(v)

assert_allclose(np.dot(h, v1), v)
assert_allclose(np.dot(h, v), v1)

In [190]:
rndm = np.random.RandomState(1234)

vec = rndm.uniform(size=7)
v1, h = householder(vec)

assert_allclose(np.dot(h, v1), vec)

# Part II. Compute the QR decomposition of a matrix.

Given a rectangular $m\times n$ matrix $\mathbf{A}$, construct a Householder reflector matrix $\mathbf{H}_1$ which transforms the first column of $\mathbf{A}$ (and call the result $\mathbf{A}^{(1)}$)

$$
\mathbf{H}_1 \mathbf{A} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
&& \dots&& \\
0      & \times & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(1)}\;.
$$

Now consider the lower-right submatrix of $\mathbf{A}^{(1)}$, and construct a Householder reflector which annihilates the second column of $\mathbf{A}$:

$$
\mathbf{H}_2 \mathbf{A}^{(1)} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & 0      & \times & \dots & \times \\
&& \dots&& \\
0      & 0      & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(2)} \;.
$$

Repeating the process $n-1$ times, we obtain

$$
\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} = \mathbf{R} \;,
$$

with $\mathbf{R}$ an upper triangular matrix. Since each $\mathbf{H}_k$ is orthogonal, so is their product. The inverse of an orthogonal matrix is orthogonal. Hence the process generates the $QR$ decomposition of $\mathbf{A}$. 

In [191]:
def qr_decomp(a):
    """Compute the QR decomposition of a matrix.
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    
    Returns
    -------
    q : ndarray, shape(m, m)
        The orthogonal matrix
    r : ndarray, shape(m, n)
        The upper triangular matrix
        
    Examples
    --------
    >>> a = np.random.random(size=(3, 5))
    >>> q, r = qr_decomp(a)
    >>> np.assert_allclose(np.dot(q, r), a)
    
    """

    a1 = np.array(a, copy=True, dtype=float)
 
    m, n = a1.shape
    H_res = np.diag(np.ones((m,)))
    for i in range (0,n):
        
        H = np.diag(np.ones(m,))
        
        H[i:,i:] = householder(a1[:,0])[1]
        a1 = H[i:,i:] @ a1
        a1 = a1[1:,1:]
        H_res = H @ H_res
       
    
    return H_res.T, (H_res @ a)
        
        
        
    
    # ENTER YOUR CODE HERE

In [192]:
# Might want to turn this on for prettier printing: zeros instead of `1e-16` etc

np.set_printoptions(suppress=True)

In [193]:
# Test (marked)

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))

q, r = qr_decomp(a)


# test that Q is indeed orthogonal
assert_allclose(np.dot(q, q.T), np.eye(5), atol=1e-10)

# test the decomposition itself
assert_allclose(np.dot(q, r), a)

Now compare your decompositions to the library function (which actually wraps the corresponding LAPACK functions)

In [194]:
from scipy.linalg import qr
qq, rr = qr(a)

print(q)
print("Library:")
print(qq)



print(r)
print("Library:")
print(rr)
assert_allclose(np.dot(qq, rr), a)

[[ 0.13665049  0.53601299 -0.09369752  0.7697136   0.30459557]
 [ 0.56035895  0.0935397  -0.53326881  0.01839528 -0.62652547]
 [ 0.19725922  0.65948912  0.60068463 -0.32384673 -0.24589462]
 [ 0.62498418 -0.50418303  0.52144688  0.28453698  0.04822969]
 [ 0.48765568  0.12171264 -0.27224305 -0.47049398  0.67223293]]
Library:
[[-0.13665049  0.53601299  0.09369752  0.661619   -0.49749149]
 [-0.56035895  0.0935397   0.53326881 -0.52477245 -0.34276292]
 [-0.19725922  0.65948912 -0.60068463 -0.37879015  0.14784752]
 [-0.62498418 -0.50418303 -0.52144688  0.18967657 -0.21750907]
 [-0.48765568  0.12171264  0.27224305  0.32774225  0.75222783]]
[[1.40152769 1.2514379  0.89523615]
 [0.         0.84158252 0.68447942]
 [0.         0.         0.5496046 ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Library:
[[-1.40152769 -1.2514379  -0.89523615]
 [ 0.          0.84158252  0.68447942]
 [ 0.          0.         -0.5496046 ]
 [ 0.          0.          0.        ]
 [ 0.        

Check if your `q` and `r` agree with `qq` and `rr`. Explain.

*Enter your explanation here (Russian or English, up to you)*

The difference between $r$ and $rr$ is that the first and the third rows have different signs. That is because every iteration of the Householder reflection $H_i$ corresponds to an also perfectly working reflection $-H_i$, and since at every new step we consider a sub-matrix excluding the "current" topmost row, there is a freedom in the sign of each row of our $R$-matrix.

$Q$'s have, at first glance, a much more drastic difference (besides the signs): the last two columns are not the same. My explanation is as follows: let us consider a working $QR$ decomposition of $A$ such that $A=QR$, and a map $Q \rightarrow Q + F$, where $F_{ij} = 0$ for $0 <= i <m$ and $0 <= j < n$, and whose last $m-n$ columns are arbitrary. It is easy to see that $(Q+F)R = R$: 

$$(FR)_{ij} =F_{ik}R^{kj} = (\sum_{k=0}^{n-1}+\sum_{k=n}^{m-1})F_{ik}R^{kj}$$

The first sum is equal to $0$ by construction, the second - due to $R$ being right-triangular. So the last $m-n$ columns don't affect the decomposition in any way (granted, $Q+F$ is still orthogonal).


# Part III. Avoid forming Householder matrices explicitly.

Note the special structure of the Householder matrices: A reflector $\mathbf{H}$ is completely specified by a reflection vector $\mathbf{u}$. Also note that the computational cost of applying a reflector to a matrix strongly depends on the order of operations:

$$
\left( \mathbf{u} \mathbf{u}^T \right) \mathbf{A}  \qquad \textrm{is } O(m^2 n)\;,
$$
while
$$
\mathbf{u} \left( \mathbf{u}^T \mathbf{A} \right) \qquad \textrm{is } O(mn)
$$

Thus, it seems to make sense to *avoid* forming the $\mathbf{H}$ matrices. Instead, one stores the reflection vectors, $\mathbf{u}$, themselves, and provides a way of multiplying an arbitrary matrix by $\mathbf{Q}^T$, e.g., as a standalone function (or a class).

Write a function which constructs the `QR` decomposition of a matrix *without ever forming the* $\mathbf{H}$ matrices, and returns the $\mathbf{R}$ matrix and reflection vectors. Write a second function, which uses the reflection vertices to multiply a matrix with $\mathbf{Q}^T$. Make sure to include enough comments for a marker to follow your implementation, and add tests.

In [195]:
def qr_eff(a):
    """Compute the QR decomposition of a matrix.
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    
    Returns
    -------
    r : ndarray, shape(m, n)
        The upper triangular matrix
    u : ndarray, shape (m, n)
        Reflection vectors
        
    Examples
    --------
    >>> a = np.random.random(size=(3, 5))
    >>> q, r = qr_eff(a)
    >>> np.assert_allclose(np.dot(q, r), a)
    
    """

    a1 = np.array(a, copy=True, dtype=float)
    a_res = np.array(a, copy=True, dtype=float)
    m, n = a1.shape
    u_res = np.zeros((m,n))
    
    for i in range (0,n):
        
        #Pretty much as before, but this time the procedure goes as described above
        
        vec = a1[:,0]
        
        y = np.zeros((len(vec)))
        y[0] = np.linalg.norm(vec)
        u = vec - y
        u /= np.linalg.norm(u)
        u_0 = np.zeros((m))
        
            
        u_0[i:] = u
        u_res[:,i] = u_0
        d = u_0[:,None].T @ a_res
        
        a_res = a_res - 2 * (u_0[:,None] @ d)
        
        a1 = a_res[i+1:,i+1:]
       
    
    return a_res, u_res

def multiply(a,u):
    """Multiply a given matrix with Q^T
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    u : ndarray, shape(m,n)
        Reflection vectors
    
    Returns
    -------
    a_res : Multiplied matrix
    
    """
   
    a_res = np.array(a, copy=True, dtype=float)
    m, n = a.shape
    
    
    for i in range (0,n):
        
        #Pretty much as before, but this time the procedure goes as described above
        d = (u[:,i])[:,None].T @ a_res
        
        a_res = a_res - 2 * ((u[:,i])[:,None] @ d)
    
    return a_res
    
        

In [196]:
# Test (marked)

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))

r, u = qr_eff(a)

print(r)

[[ 1.40152769  1.2514379   0.89523615]
 [ 0.          0.84158252  0.68447942]
 [-0.          0.          0.5496046 ]
 [ 0.          0.          0.        ]
 [ 0.          0.         -0.        ]]


We see that the $R$-matrix is the same as before

In [197]:
print(a)
print(multiply(a,u))


[[0.19151945 0.62210877 0.43772774]
 [0.78535858 0.77997581 0.27259261]
 [0.27646426 0.80187218 0.95813935]
 [0.87593263 0.35781727 0.50099513]
 [0.68346294 0.71270203 0.37025075]]
[[ 1.40152769  1.2514379   0.89523615]
 [ 0.          0.84158252  0.68447942]
 [-0.          0.          0.5496046 ]
 [ 0.          0.          0.        ]
 [ 0.          0.         -0.        ]]


The first matrix is the given one, the second one is equal to $Q^TA$