# Якоби

Наша сделка будет простой. Покажи пальцем на симметричную действительнозначную матрицу, а я разберу ее на собственные значения. Разумеется, без свидетелей и без лишнего шума. По рукам?

In [91]:
import numpy as np

def rotate (a, i, j, t):
    n, q = np.shape(a)
    res = np.diag(np.ones(n,))
    res[i][i] = np.cos(t)
    res[j][j] = np.cos(t)
    res[i][j] = -np.sin(t)
    res[j][i] = np.sin(t)
    
    return res @ a @ res.T
def jacob (a, nsweeps = 4):
    n, q = np.shape(a)
    for z in range (0,nsweeps*n):
        m = - np.inf
        i = 0
        j = 0
        for s in range(0,n):
            for q in range(s+1,n):
              
                 if(np.abs(a[s,q]) > m):
                    i = s
                    j = q
                    m = np.abs(a[s,q])

        if(a[j,j]==a[i,i]):
            t = np.pi/4
        else:
            t = 1/2 * (np.arctan(2*a[i,j]/(a[j,j]-a[i,i])))
        a = rotate(a, i, j, t)
        a[i,j] = 0
        a[j,i] = 0 
        
  
       
    v = {a[x,x] for x in range(0,n)}
    return v


Хочешь взглянуть, на что я способен?

In [92]:
a = np.asarray((2, 1, 1, 2))
a = np.reshape(a,(2,2))

print(a)
print(jacob(a))
    

[[2 1]
 [1 2]]
{1.0000000000000002, 3.0000000000000004}


Не впечатлен? Другой пример.

In [93]:
a = np.asarray((5,1,2,1,4,3,2,3,1))
a = np.reshape(a,(3,3))
print(a)

print(jacob(a))

[[5 1 2]
 [1 4 3]
 [2 3 1]]
{3.658439943003212, -1.1016973093695381, 7.443257366366328}
